// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zos.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_zos_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_zos_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_zos_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_zos_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zos_2eproto;
namespace zos {
namespace pb {
class EndPoint;
class EndPointDefaultTypeInternal;
extern EndPointDefaultTypeInternal _EndPoint_default_instance_;
class Info;
class InfoDefaultTypeInternal;
extern InfoDefaultTypeInternal _Info_default_instance_;
class State;
class StateDefaultTypeInternal;
extern StateDefaultTypeInternal _State_default_instance_;
}  // namespace pb
}  // namespace zos
PROTOBUF_NAMESPACE_OPEN
template<> ::zos::pb::EndPoint* Arena::CreateMaybeMessage<::zos::pb::EndPoint>(Arena*);
template<> ::zos::pb::Info* Arena::CreateMaybeMessage<::zos::pb::Info>(Arena*);
template<> ::zos::pb::State* Arena::CreateMaybeMessage<::zos::pb::State>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace zos {
namespace pb {

enum Info_Type : int {
  Info_Type_UNKNOWN = 0,
  Info_Type_PUB = 1,
  Info_Type_SUB = 2,
  Info_Type_LINK = 3,
  Info_Type_Info_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Info_Type_Info_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Info_Type_IsValid(int value);
constexpr Info_Type Info_Type_Type_MIN = Info_Type_UNKNOWN;
constexpr Info_Type Info_Type_Type_MAX = Info_Type_LINK;
constexpr int Info_Type_Type_ARRAYSIZE = Info_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Info_Type_descriptor();
template<typename T>
inline const std::string& Info_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Info_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Info_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Info_Type_descriptor(), enum_t_value);
}
inline bool Info_Type_Parse(
    const std::string& name, Info_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Info_Type>(
    Info_Type_descriptor(), name, value);
}
enum State_ProcessState : int {
  State_ProcessState_P_UNKNOWN = 0,
  State_ProcessState_P_STARTING = 1,
  State_ProcessState_P_RUNNING = 2,
  State_ProcessState_P_EXITING = 3,
  State_ProcessState_State_ProcessState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  State_ProcessState_State_ProcessState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool State_ProcessState_IsValid(int value);
constexpr State_ProcessState State_ProcessState_ProcessState_MIN = State_ProcessState_P_UNKNOWN;
constexpr State_ProcessState State_ProcessState_ProcessState_MAX = State_ProcessState_P_EXITING;
constexpr int State_ProcessState_ProcessState_ARRAYSIZE = State_ProcessState_ProcessState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* State_ProcessState_descriptor();
template<typename T>
inline const std::string& State_ProcessState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, State_ProcessState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function State_ProcessState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    State_ProcessState_descriptor(), enum_t_value);
}
inline bool State_ProcessState_Parse(
    const std::string& name, State_ProcessState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<State_ProcessState>(
    State_ProcessState_descriptor(), name, value);
}
// ===================================================================

class Info PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zos.pb.Info) */ {
 public:
  inline Info() : Info(nullptr) {};
  virtual ~Info();

  Info(const Info& from);
  Info(Info&& from) noexcept
    : Info() {
    *this = ::std::move(from);
  }

  inline Info& operator=(const Info& from) {
    CopyFrom(from);
    return *this;
  }
  inline Info& operator=(Info&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Info& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Info* internal_default_instance() {
    return reinterpret_cast<const Info*>(
               &_Info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Info& a, Info& b) {
    a.Swap(&b);
  }
  inline void Swap(Info* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Info* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Info* New() const final {
    return CreateMaybeMessage<Info>(nullptr);
  }

  Info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Info>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Info& from);
  void MergeFrom(const Info& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Info* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zos.pb.Info";
  }
  protected:
  explicit Info(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_zos_2eproto);
    return ::descriptor_table_zos_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Info_Type Type;
  static constexpr Type UNKNOWN =
    Info_Type_UNKNOWN;
  static constexpr Type PUB =
    Info_Type_PUB;
  static constexpr Type SUB =
    Info_Type_SUB;
  static constexpr Type LINK =
    Info_Type_LINK;
  static inline bool Type_IsValid(int value) {
    return Info_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Info_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Info_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Info_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Info_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Info_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Info_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSubNamesFieldNumber = 5,
    kMsgNameFieldNumber = 2,
    kNameFieldNumber = 3,
    kPubNameFieldNumber = 4,
    kTypeFieldNumber = 1,
  };
  // repeated string sub_names = 5;
  int sub_names_size() const;
  private:
  int _internal_sub_names_size() const;
  public:
  void clear_sub_names();
  const std::string& sub_names(int index) const;
  std::string* mutable_sub_names(int index);
  void set_sub_names(int index, const std::string& value);
  void set_sub_names(int index, std::string&& value);
  void set_sub_names(int index, const char* value);
  void set_sub_names(int index, const char* value, size_t size);
  std::string* add_sub_names();
  void add_sub_names(const std::string& value);
  void add_sub_names(std::string&& value);
  void add_sub_names(const char* value);
  void add_sub_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& sub_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_sub_names();
  private:
  const std::string& _internal_sub_names(int index) const;
  std::string* _internal_add_sub_names();
  public:

  // string msg_name = 2;
  void clear_msg_name();
  const std::string& msg_name() const;
  void set_msg_name(const std::string& value);
  void set_msg_name(std::string&& value);
  void set_msg_name(const char* value);
  void set_msg_name(const char* value, size_t size);
  std::string* mutable_msg_name();
  std::string* release_msg_name();
  void set_allocated_msg_name(std::string* msg_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_msg_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_msg_name(
      std::string* msg_name);
  private:
  const std::string& _internal_msg_name() const;
  void _internal_set_msg_name(const std::string& value);
  std::string* _internal_mutable_msg_name();
  public:

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string pub_name = 4;
  void clear_pub_name();
  const std::string& pub_name() const;
  void set_pub_name(const std::string& value);
  void set_pub_name(std::string&& value);
  void set_pub_name(const char* value);
  void set_pub_name(const char* value, size_t size);
  std::string* mutable_pub_name();
  std::string* release_pub_name();
  void set_allocated_pub_name(std::string* pub_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_pub_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_pub_name(
      std::string* pub_name);
  private:
  const std::string& _internal_pub_name() const;
  void _internal_set_pub_name(const std::string& value);
  std::string* _internal_mutable_pub_name();
  public:

  // .zos.pb.Info.Type type = 1;
  void clear_type();
  ::zos::pb::Info_Type type() const;
  void set_type(::zos::pb::Info_Type value);
  private:
  ::zos::pb::Info_Type _internal_type() const;
  void _internal_set_type(::zos::pb::Info_Type value);
  public:

  // @@protoc_insertion_point(class_scope:zos.pb.Info)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> sub_names_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pub_name_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zos_2eproto;
};
// -------------------------------------------------------------------

class EndPoint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zos.pb.EndPoint) */ {
 public:
  inline EndPoint() : EndPoint(nullptr) {};
  virtual ~EndPoint();

  EndPoint(const EndPoint& from);
  EndPoint(EndPoint&& from) noexcept
    : EndPoint() {
    *this = ::std::move(from);
  }

  inline EndPoint& operator=(const EndPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline EndPoint& operator=(EndPoint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EndPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EndPoint* internal_default_instance() {
    return reinterpret_cast<const EndPoint*>(
               &_EndPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EndPoint& a, EndPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(EndPoint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EndPoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EndPoint* New() const final {
    return CreateMaybeMessage<EndPoint>(nullptr);
  }

  EndPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EndPoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EndPoint& from);
  void MergeFrom(const EndPoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EndPoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zos.pb.EndPoint";
  }
  protected:
  explicit EndPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_zos_2eproto);
    return ::descriptor_table_zos_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string address = 1;
  void clear_address();
  const std::string& address() const;
  void set_address(const std::string& value);
  void set_address(std::string&& value);
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  std::string* mutable_address();
  std::string* release_address();
  void set_allocated_address(std::string* address);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_address();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_address(
      std::string* address);
  private:
  const std::string& _internal_address() const;
  void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // int32 port = 2;
  void clear_port();
  ::PROTOBUF_NAMESPACE_ID::int32 port() const;
  void set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_port() const;
  void _internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:zos.pb.EndPoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::int32 port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zos_2eproto;
};
// -------------------------------------------------------------------

class State PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zos.pb.State) */ {
 public:
  inline State() : State(nullptr) {};
  virtual ~State();

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const State& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline State* New() const final {
    return CreateMaybeMessage<State>(nullptr);
  }

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<State>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const State& from);
  void MergeFrom(const State& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zos.pb.State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_zos_2eproto);
    return ::descriptor_table_zos_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef State_ProcessState ProcessState;
  static constexpr ProcessState P_UNKNOWN =
    State_ProcessState_P_UNKNOWN;
  static constexpr ProcessState P_STARTING =
    State_ProcessState_P_STARTING;
  static constexpr ProcessState P_RUNNING =
    State_ProcessState_P_RUNNING;
  static constexpr ProcessState P_EXITING =
    State_ProcessState_P_EXITING;
  static inline bool ProcessState_IsValid(int value) {
    return State_ProcessState_IsValid(value);
  }
  static constexpr ProcessState ProcessState_MIN =
    State_ProcessState_ProcessState_MIN;
  static constexpr ProcessState ProcessState_MAX =
    State_ProcessState_ProcessState_MAX;
  static constexpr int ProcessState_ARRAYSIZE =
    State_ProcessState_ProcessState_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ProcessState_descriptor() {
    return State_ProcessState_descriptor();
  }
  template<typename T>
  static inline const std::string& ProcessState_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ProcessState>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ProcessState_Name.");
    return State_ProcessState_Name(enum_t_value);
  }
  static inline bool ProcessState_Parse(const std::string& name,
      ProcessState* value) {
    return State_ProcessState_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kInfosFieldNumber = 5,
    kNameFieldNumber = 2,
    kEpFieldNumber = 4,
    kPidFieldNumber = 1,
    kStateFieldNumber = 3,
  };
  // repeated .zos.pb.Info infos = 5;
  int infos_size() const;
  private:
  int _internal_infos_size() const;
  public:
  void clear_infos();
  ::zos::pb::Info* mutable_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zos::pb::Info >*
      mutable_infos();
  private:
  const ::zos::pb::Info& _internal_infos(int index) const;
  ::zos::pb::Info* _internal_add_infos();
  public:
  const ::zos::pb::Info& infos(int index) const;
  ::zos::pb::Info* add_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zos::pb::Info >&
      infos() const;

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .zos.pb.EndPoint ep = 4;
  bool has_ep() const;
  private:
  bool _internal_has_ep() const;
  public:
  void clear_ep();
  const ::zos::pb::EndPoint& ep() const;
  ::zos::pb::EndPoint* release_ep();
  ::zos::pb::EndPoint* mutable_ep();
  void set_allocated_ep(::zos::pb::EndPoint* ep);
  private:
  const ::zos::pb::EndPoint& _internal_ep() const;
  ::zos::pb::EndPoint* _internal_mutable_ep();
  public:
  void unsafe_arena_set_allocated_ep(
      ::zos::pb::EndPoint* ep);
  ::zos::pb::EndPoint* unsafe_arena_release_ep();

  // int32 pid = 1;
  void clear_pid();
  ::PROTOBUF_NAMESPACE_ID::int32 pid() const;
  void set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pid() const;
  void _internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .zos.pb.State.ProcessState state = 3;
  void clear_state();
  ::zos::pb::State_ProcessState state() const;
  void set_state(::zos::pb::State_ProcessState value);
  private:
  ::zos::pb::State_ProcessState _internal_state() const;
  void _internal_set_state(::zos::pb::State_ProcessState value);
  public:

  // @@protoc_insertion_point(class_scope:zos.pb.State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zos::pb::Info > infos_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::zos::pb::EndPoint* ep_;
  ::PROTOBUF_NAMESPACE_ID::int32 pid_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zos_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Info

// .zos.pb.Info.Type type = 1;
inline void Info::clear_type() {
  type_ = 0;
}
inline ::zos::pb::Info_Type Info::_internal_type() const {
  return static_cast< ::zos::pb::Info_Type >(type_);
}
inline ::zos::pb::Info_Type Info::type() const {
  // @@protoc_insertion_point(field_get:zos.pb.Info.type)
  return _internal_type();
}
inline void Info::_internal_set_type(::zos::pb::Info_Type value) {
  
  type_ = value;
}
inline void Info::set_type(::zos::pb::Info_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:zos.pb.Info.type)
}

// string msg_name = 2;
inline void Info::clear_msg_name() {
  msg_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Info::msg_name() const {
  // @@protoc_insertion_point(field_get:zos.pb.Info.msg_name)
  return _internal_msg_name();
}
inline void Info::set_msg_name(const std::string& value) {
  _internal_set_msg_name(value);
  // @@protoc_insertion_point(field_set:zos.pb.Info.msg_name)
}
inline std::string* Info::mutable_msg_name() {
  // @@protoc_insertion_point(field_mutable:zos.pb.Info.msg_name)
  return _internal_mutable_msg_name();
}
inline const std::string& Info::_internal_msg_name() const {
  return msg_name_.Get();
}
inline void Info::_internal_set_msg_name(const std::string& value) {
  
  msg_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Info::set_msg_name(std::string&& value) {
  
  msg_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zos.pb.Info.msg_name)
}
inline void Info::set_msg_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zos.pb.Info.msg_name)
}
inline void Info::set_msg_name(const char* value,
    size_t size) {
  
  msg_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zos.pb.Info.msg_name)
}
inline std::string* Info::_internal_mutable_msg_name() {
  
  return msg_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Info::release_msg_name() {
  // @@protoc_insertion_point(field_release:zos.pb.Info.msg_name)
  return msg_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Info::set_allocated_msg_name(std::string* msg_name) {
  if (msg_name != nullptr) {
    
  } else {
    
  }
  msg_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zos.pb.Info.msg_name)
}
inline std::string* Info::unsafe_arena_release_msg_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zos.pb.Info.msg_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return msg_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Info::unsafe_arena_set_allocated_msg_name(
    std::string* msg_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (msg_name != nullptr) {
    
  } else {
    
  }
  msg_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      msg_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.Info.msg_name)
}

// string name = 3;
inline void Info::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Info::name() const {
  // @@protoc_insertion_point(field_get:zos.pb.Info.name)
  return _internal_name();
}
inline void Info::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:zos.pb.Info.name)
}
inline std::string* Info::mutable_name() {
  // @@protoc_insertion_point(field_mutable:zos.pb.Info.name)
  return _internal_mutable_name();
}
inline const std::string& Info::_internal_name() const {
  return name_.Get();
}
inline void Info::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Info::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zos.pb.Info.name)
}
inline void Info::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zos.pb.Info.name)
}
inline void Info::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zos.pb.Info.name)
}
inline std::string* Info::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Info::release_name() {
  // @@protoc_insertion_point(field_release:zos.pb.Info.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Info::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zos.pb.Info.name)
}
inline std::string* Info::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zos.pb.Info.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Info::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.Info.name)
}

// string pub_name = 4;
inline void Info::clear_pub_name() {
  pub_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Info::pub_name() const {
  // @@protoc_insertion_point(field_get:zos.pb.Info.pub_name)
  return _internal_pub_name();
}
inline void Info::set_pub_name(const std::string& value) {
  _internal_set_pub_name(value);
  // @@protoc_insertion_point(field_set:zos.pb.Info.pub_name)
}
inline std::string* Info::mutable_pub_name() {
  // @@protoc_insertion_point(field_mutable:zos.pb.Info.pub_name)
  return _internal_mutable_pub_name();
}
inline const std::string& Info::_internal_pub_name() const {
  return pub_name_.Get();
}
inline void Info::_internal_set_pub_name(const std::string& value) {
  
  pub_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Info::set_pub_name(std::string&& value) {
  
  pub_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zos.pb.Info.pub_name)
}
inline void Info::set_pub_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pub_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zos.pb.Info.pub_name)
}
inline void Info::set_pub_name(const char* value,
    size_t size) {
  
  pub_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zos.pb.Info.pub_name)
}
inline std::string* Info::_internal_mutable_pub_name() {
  
  return pub_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Info::release_pub_name() {
  // @@protoc_insertion_point(field_release:zos.pb.Info.pub_name)
  return pub_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Info::set_allocated_pub_name(std::string* pub_name) {
  if (pub_name != nullptr) {
    
  } else {
    
  }
  pub_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pub_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zos.pb.Info.pub_name)
}
inline std::string* Info::unsafe_arena_release_pub_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zos.pb.Info.pub_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return pub_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Info::unsafe_arena_set_allocated_pub_name(
    std::string* pub_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (pub_name != nullptr) {
    
  } else {
    
  }
  pub_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      pub_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.Info.pub_name)
}

// repeated string sub_names = 5;
inline int Info::_internal_sub_names_size() const {
  return sub_names_.size();
}
inline int Info::sub_names_size() const {
  return _internal_sub_names_size();
}
inline void Info::clear_sub_names() {
  sub_names_.Clear();
}
inline std::string* Info::add_sub_names() {
  // @@protoc_insertion_point(field_add_mutable:zos.pb.Info.sub_names)
  return _internal_add_sub_names();
}
inline const std::string& Info::_internal_sub_names(int index) const {
  return sub_names_.Get(index);
}
inline const std::string& Info::sub_names(int index) const {
  // @@protoc_insertion_point(field_get:zos.pb.Info.sub_names)
  return _internal_sub_names(index);
}
inline std::string* Info::mutable_sub_names(int index) {
  // @@protoc_insertion_point(field_mutable:zos.pb.Info.sub_names)
  return sub_names_.Mutable(index);
}
inline void Info::set_sub_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:zos.pb.Info.sub_names)
  sub_names_.Mutable(index)->assign(value);
}
inline void Info::set_sub_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:zos.pb.Info.sub_names)
  sub_names_.Mutable(index)->assign(std::move(value));
}
inline void Info::set_sub_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  sub_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:zos.pb.Info.sub_names)
}
inline void Info::set_sub_names(int index, const char* value, size_t size) {
  sub_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:zos.pb.Info.sub_names)
}
inline std::string* Info::_internal_add_sub_names() {
  return sub_names_.Add();
}
inline void Info::add_sub_names(const std::string& value) {
  sub_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:zos.pb.Info.sub_names)
}
inline void Info::add_sub_names(std::string&& value) {
  sub_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:zos.pb.Info.sub_names)
}
inline void Info::add_sub_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  sub_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:zos.pb.Info.sub_names)
}
inline void Info::add_sub_names(const char* value, size_t size) {
  sub_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:zos.pb.Info.sub_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Info::sub_names() const {
  // @@protoc_insertion_point(field_list:zos.pb.Info.sub_names)
  return sub_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Info::mutable_sub_names() {
  // @@protoc_insertion_point(field_mutable_list:zos.pb.Info.sub_names)
  return &sub_names_;
}

// -------------------------------------------------------------------

// EndPoint

// string address = 1;
inline void EndPoint::clear_address() {
  address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EndPoint::address() const {
  // @@protoc_insertion_point(field_get:zos.pb.EndPoint.address)
  return _internal_address();
}
inline void EndPoint::set_address(const std::string& value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:zos.pb.EndPoint.address)
}
inline std::string* EndPoint::mutable_address() {
  // @@protoc_insertion_point(field_mutable:zos.pb.EndPoint.address)
  return _internal_mutable_address();
}
inline const std::string& EndPoint::_internal_address() const {
  return address_.Get();
}
inline void EndPoint::_internal_set_address(const std::string& value) {
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EndPoint::set_address(std::string&& value) {
  
  address_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zos.pb.EndPoint.address)
}
inline void EndPoint::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zos.pb.EndPoint.address)
}
inline void EndPoint::set_address(const char* value,
    size_t size) {
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zos.pb.EndPoint.address)
}
inline std::string* EndPoint::_internal_mutable_address() {
  
  return address_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EndPoint::release_address() {
  // @@protoc_insertion_point(field_release:zos.pb.EndPoint.address)
  return address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndPoint::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zos.pb.EndPoint.address)
}
inline std::string* EndPoint::unsafe_arena_release_address() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zos.pb.EndPoint.address)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return address_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EndPoint::unsafe_arena_set_allocated_address(
    std::string* address) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (address != nullptr) {
    
  } else {
    
  }
  address_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      address, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.EndPoint.address)
}

// int32 port = 2;
inline void EndPoint::clear_port() {
  port_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EndPoint::_internal_port() const {
  return port_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EndPoint::port() const {
  // @@protoc_insertion_point(field_get:zos.pb.EndPoint.port)
  return _internal_port();
}
inline void EndPoint::_internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  port_ = value;
}
inline void EndPoint::set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:zos.pb.EndPoint.port)
}

// -------------------------------------------------------------------

// State

// int32 pid = 1;
inline void State::clear_pid() {
  pid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 State::_internal_pid() const {
  return pid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 State::pid() const {
  // @@protoc_insertion_point(field_get:zos.pb.State.pid)
  return _internal_pid();
}
inline void State::_internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pid_ = value;
}
inline void State::set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:zos.pb.State.pid)
}

// string name = 2;
inline void State::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& State::name() const {
  // @@protoc_insertion_point(field_get:zos.pb.State.name)
  return _internal_name();
}
inline void State::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:zos.pb.State.name)
}
inline std::string* State::mutable_name() {
  // @@protoc_insertion_point(field_mutable:zos.pb.State.name)
  return _internal_mutable_name();
}
inline const std::string& State::_internal_name() const {
  return name_.Get();
}
inline void State::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void State::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zos.pb.State.name)
}
inline void State::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zos.pb.State.name)
}
inline void State::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zos.pb.State.name)
}
inline std::string* State::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* State::release_name() {
  // @@protoc_insertion_point(field_release:zos.pb.State.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void State::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zos.pb.State.name)
}
inline std::string* State::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zos.pb.State.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void State::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.State.name)
}

// .zos.pb.State.ProcessState state = 3;
inline void State::clear_state() {
  state_ = 0;
}
inline ::zos::pb::State_ProcessState State::_internal_state() const {
  return static_cast< ::zos::pb::State_ProcessState >(state_);
}
inline ::zos::pb::State_ProcessState State::state() const {
  // @@protoc_insertion_point(field_get:zos.pb.State.state)
  return _internal_state();
}
inline void State::_internal_set_state(::zos::pb::State_ProcessState value) {
  
  state_ = value;
}
inline void State::set_state(::zos::pb::State_ProcessState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:zos.pb.State.state)
}

// .zos.pb.EndPoint ep = 4;
inline bool State::_internal_has_ep() const {
  return this != internal_default_instance() && ep_ != nullptr;
}
inline bool State::has_ep() const {
  return _internal_has_ep();
}
inline void State::clear_ep() {
  if (GetArena() == nullptr && ep_ != nullptr) {
    delete ep_;
  }
  ep_ = nullptr;
}
inline const ::zos::pb::EndPoint& State::_internal_ep() const {
  const ::zos::pb::EndPoint* p = ep_;
  return p != nullptr ? *p : *reinterpret_cast<const ::zos::pb::EndPoint*>(
      &::zos::pb::_EndPoint_default_instance_);
}
inline const ::zos::pb::EndPoint& State::ep() const {
  // @@protoc_insertion_point(field_get:zos.pb.State.ep)
  return _internal_ep();
}
inline void State::unsafe_arena_set_allocated_ep(
    ::zos::pb::EndPoint* ep) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ep_);
  }
  ep_ = ep;
  if (ep) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zos.pb.State.ep)
}
inline ::zos::pb::EndPoint* State::release_ep() {
  auto temp = unsafe_arena_release_ep();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::zos::pb::EndPoint* State::unsafe_arena_release_ep() {
  // @@protoc_insertion_point(field_release:zos.pb.State.ep)
  
  ::zos::pb::EndPoint* temp = ep_;
  ep_ = nullptr;
  return temp;
}
inline ::zos::pb::EndPoint* State::_internal_mutable_ep() {
  
  if (ep_ == nullptr) {
    auto* p = CreateMaybeMessage<::zos::pb::EndPoint>(GetArena());
    ep_ = p;
  }
  return ep_;
}
inline ::zos::pb::EndPoint* State::mutable_ep() {
  // @@protoc_insertion_point(field_mutable:zos.pb.State.ep)
  return _internal_mutable_ep();
}
inline void State::set_allocated_ep(::zos::pb::EndPoint* ep) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete ep_;
  }
  if (ep) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(ep);
    if (message_arena != submessage_arena) {
      ep = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ep, submessage_arena);
    }
    
  } else {
    
  }
  ep_ = ep;
  // @@protoc_insertion_point(field_set_allocated:zos.pb.State.ep)
}

// repeated .zos.pb.Info infos = 5;
inline int State::_internal_infos_size() const {
  return infos_.size();
}
inline int State::infos_size() const {
  return _internal_infos_size();
}
inline void State::clear_infos() {
  infos_.Clear();
}
inline ::zos::pb::Info* State::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:zos.pb.State.infos)
  return infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zos::pb::Info >*
State::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:zos.pb.State.infos)
  return &infos_;
}
inline const ::zos::pb::Info& State::_internal_infos(int index) const {
  return infos_.Get(index);
}
inline const ::zos::pb::Info& State::infos(int index) const {
  // @@protoc_insertion_point(field_get:zos.pb.State.infos)
  return _internal_infos(index);
}
inline ::zos::pb::Info* State::_internal_add_infos() {
  return infos_.Add();
}
inline ::zos::pb::Info* State::add_infos() {
  // @@protoc_insertion_point(field_add:zos.pb.State.infos)
  return _internal_add_infos();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zos::pb::Info >&
State::infos() const {
  // @@protoc_insertion_point(field_list:zos.pb.State.infos)
  return infos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace zos

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::zos::pb::Info_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zos::pb::Info_Type>() {
  return ::zos::pb::Info_Type_descriptor();
}
template <> struct is_proto_enum< ::zos::pb::State_ProcessState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zos::pb::State_ProcessState>() {
  return ::zos::pb::State_ProcessState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_zos_2eproto
