#!/usr/bin/env python3
import os, re

# get all tactic package name from ../tactic_packages.txt
def get_tactic_packages(file_path):
    tactic_packages = []
    with open(file_path, "r") as f:
        for line in f:
            tactic_packages.append(line.strip())
    return tactic_packages

if __name__ == '__main__':
    current_path = os.path.dirname(os.path.abspath(__file__))
    tactic_packages_name_file_path = os.path.join(current_path, "../tactic_packages.txt")
    tactic_name_list = get_tactic_packages(tactic_packages_name_file_path)
    tactic_path = os.path.join(current_path, "../../Core/")
    for tactic_name in tactic_name_list:
        ref_config_file = os.path.join(tactic_path, tactic_name, "PlayConfig.lua")
        if not os.path.exists(ref_config_file):
            continue
        print(tactic_name)