#!/usr/bin/env python3
import os, re

# get all tactic package name from ../tactic_packages.txt
def get_tactic_packages(file_path):
    tactic_packages = []
    with open(file_path, "r") as f:
        for line in f:
            tactic_packages.append(line.strip())
    return tactic_packages

# get all file name in current dir
def get_all_files(dir):
    files = []
    for root, dirs, file in os.walk(dir):
        for f in file:
            # files.append(os.path.abspath(os.path.join(root, f)))
            files.append(f)
    # sort
    files.sort()
    return files

if __name__ == '__main__':
    # get current file path
    current_path = os.path.dirname(os.path.abspath(__file__))
    tactic_packages_name_file_path = os.path.join(current_path, "../tactic_packages.txt")
    tactic_name_list = get_tactic_packages(tactic_packages_name_file_path)
    tactic_path = os.path.join(current_path, "../../Core/")
    for tactic_name in tactic_name_list:
        tactic_dir = os.path.join(tactic_path, tactic_name, "play")
        if not os.path.exists(tactic_dir):
            # print("tactic package {} not exists".format(tactic_dir))
            continue
        # get all file name in tactic package
        files = get_all_files(tactic_dir)
        # print("tactic package {} has {} files".format(tactic_name, len(files)))
        for file in files:
            # check if file is .lua file
            if not file.endswith(".lua"):
                continue
            # get file content and get 'name = "TestName"' line using regex
            file_path = os.path.join(tactic_dir, file)
            with open(file_path, "r") as f:
                content = f.read().split('\n')
                for line in content:
                    line = line.replace(' ','')
                    if "name" in line and line.startswith("name=") and line.endswith(","):
                        # get name value in "" or ''
                        name = re.findall(r'name=(?:"|\')(.*?)(?:"|\')', line)
                        if len(name) == 0:
                            continue
                        print(name[0])
                        break

            # print("{}\t{}".format(tactic_name,file))
            # print(file)